import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';
import { ConfigBasePage } from '@pages/configuration/ConfigBasePage';

export type DealDetailsData = {
    title: string;
    desc: string;
    fullDesc: string;
    keywords: string[];
    startDate: string;
    endDate: string;
    startHour: string;
    startMin: string;
    endHour: string;
    endMin: string;
    dealValue: string;
    minimumSpend: string;
    currentQuantity?: string;
    unlimitedQuantity?: boolean;
    terms?: string;
    resetToAutoGenerated?: boolean;
};

/**
 * The manual deal builder is a single "deal editor and design studio" page:
 * Details, Designs, Brand and Finish are sections of one form, and "Create
 * Deal" validates and submits the whole thing. There is no longer a separate
 * details step, design step, or "Next" button.
 *
 * Fields carry no id, aria-label or test id, so they are located through the
 * one stable contract the markup does offer: each field sits in a `.form-group`
 * alongside its own `label.form-label`. Everything is scoped to the studio
 * region so the NJoyBuild panel's inputs can never be matched by accident.
 */
export class DealStudio extends ConfigBasePage {
    private readonly studio: Locator;
    private readonly fieldGroups: Locator;

    private readonly dealTitleInput: Locator;
    private readonly descriptionInput: Locator;
    private readonly fullDescriptionEditor: Locator;
    private readonly keywordsInput: Locator;
    private readonly keywordLimitMessage: Locator;

    private readonly allBranchesCheckbox: Locator;

    private readonly noExpiryToggle: Locator;
    private readonly startDateInput: Locator;
    private readonly endDateInput: Locator;
    private readonly startTimeInput: Locator;
    private readonly endTimeInput: Locator;

    private readonly dealValueTypeSelect: Locator;
    private readonly dealValueInput: Locator;
    private readonly currencySelect: Locator;
    private readonly minimumSpendInput: Locator;
    private readonly unlimitedQuantityToggle: Locator;
    private readonly currentQuantityInput: Locator;

    private readonly termsEditor: Locator;
    private readonly resetTermsButton: Locator;

    private readonly validationAlert: Locator;
    private readonly createDealButton: Locator;

    constructor(page: Page) {
        super(page);
        this.studio = this.page.getByRole('region', { name: 'Deal editor and design studio' });
        this.fieldGroups = this.studio.locator('.form-group');

        this.dealTitleInput = this.field('Deal title').getByRole('textbox');
        this.descriptionInput = this.field('Description').getByRole('textbox');
        this.fullDescriptionEditor = this.field('Full description').locator('.tiptap');
        this.keywordsInput = this.studio.getByRole('textbox', { name: /Type keywords/ });
        this.keywordLimitMessage = this.studio.getByText('Maximum 7 keywords allowed');

        this.allBranchesCheckbox = this.studio.getByRole('checkbox', { name: 'All branches' });

        this.noExpiryToggle = this.studio.getByRole('switch', { name: 'Make deal indefinite' });
        // Start/end date and time share a placeholder-derived accessible name and
        // have no per-field label association. The form renders start before end
        // in both pairs, which is the visible ordering users rely on too.
        this.startDateInput = this.studio.getByRole('textbox', { name: 'YYYY-MM-DD' }).first();
        this.endDateInput = this.studio.getByRole('textbox', { name: 'YYYY-MM-DD' }).nth(1);
        this.startTimeInput = this.studio.getByRole('textbox', { name: 'Select time' }).first();
        this.endTimeInput = this.studio.getByRole('textbox', { name: 'Select time' }).nth(1);

        this.dealValueTypeSelect = this.field('Deal value').getByRole('combobox').first();
        this.dealValueInput = this.field('Deal value').getByRole('spinbutton');
        this.currencySelect = this.field('Currency').getByRole('combobox');
        this.minimumSpendInput = this.field('Minimum spend').getByRole('spinbutton');
        // This toggle's group has no label element, so it is identified by the
        // "Unlimited quantity" copy that heads the group.
        this.unlimitedQuantityToggle = this.fieldGroups
            .filter({ hasText: /^Unlimited quantity/ })
            .getByRole('switch');
        this.currentQuantityInput = this.field('Current quantity').getByRole('spinbutton');

        this.termsEditor = this.field('Terms content').locator('.tiptap');
        this.resetTermsButton = this.studio.getByRole('button', { name: 'Reset to auto-generated' });

        this.validationAlert = this.page.getByRole('alert', { name: 'Please fix the following fields' });
        this.createDealButton = this.page.getByRole('button', { name: 'Create Deal' });
    }

    /**
     * Resolves a field by its visible label. Anchored at the start of the label
     * so "Description" cannot also match "Full description".
     */
    private field(label: string): Locator {
        return this.fieldGroups.filter({
            has: this.page.locator('label.form-label').filter({ hasText: new RegExp(`^\\s*${label}\\b`) }),
        });
    }

    override async waitForReady(): Promise<void> {
        await super.waitForReady();
        await expect(this.studio).toBeVisible();
        await expect(this.dealTitleInput).toBeVisible();
    }

    async fill(data: DealDetailsData): Promise<void> {
        await this.fillDealTitle(data.title);
        await this.fillDescription(data.desc);
        await this.fillFullDescription(data.fullDesc);
        await this.addKeywords(data.keywords);

        await this.fillStartDate(data.startDate);
        await this.fillEndDate(data.endDate);
        await this.fillStartTime(data.startHour, data.startMin);
        await this.fillEndTime(data.endHour, data.endMin);

        await this.fillDealValue(data.dealValue);
        await this.fillMinimumSpend(data.minimumSpend);
        if (!data.unlimitedQuantity && data.currentQuantity) {
            await this.toggleUnlimitedQuantity();
            await this.fillCurrentQuantity(data.currentQuantity);
        }

        if (data.resetToAutoGenerated) {
            await this.resetTermsAndConditions();
        }
        if (data.terms !== undefined) {
            await this.fillTermsAndConditions(data.terms);
        }
    }

    /**
     * Submits the studio. On success the app leaves the builder for the new
     * deal's detail page, which is the observable outcome we assert on.
     */
    async submitAndExpectSuccess(): Promise<void> {
        await this.createDealButton.click();
        await expect(this.page).toHaveURL(/\/configuration\/deal\/deal_/);
    }

    async submitExpectingValidationError(): Promise<void> {
        await this.createDealButton.click();
        await expect(this.validationAlert).toBeVisible();
    }

    /**
     * The studio reports validation as one summary toast that bullets each
     * offending field, so assertions name the field rather than a per-input
     * message.
     */
    async expectValidationFor(fieldName: string): Promise<void> {
        await expect(this.validationAlert).toBeVisible();
        await expect(this.validationAlert).toContainText(`• ${fieldName}`);
    }

    async expectTitleValidationError(): Promise<void> {
        await this.expectValidationFor('Title');
    }

    async expectDescriptionValidationError(): Promise<void> {
        await this.expectValidationFor('Description');
    }

    async expectStartDateValidationError(): Promise<void> {
        await this.expectValidationFor('Start date');
    }

    async expectEndDateValidationError(): Promise<void> {
        await this.expectValidationFor('End date');
    }

    async expectDealValueValidationError(): Promise<void> {
        await this.expectValidationFor('Deal value');
    }

    async expectQuantityValidationError(): Promise<void> {
        await this.expectValidationFor('Quantity');
    }

    async expectTermsRequiredError(): Promise<void> {
        await this.expectValidationFor('Terms & Conditions');
    }

    async verifyKeywordLimit(): Promise<void> {
        await expect(this.keywordLimitMessage).toBeVisible();
    }

    async fillDealTitle(value: string): Promise<void> {
        await this.dealTitleInput.fill(value);
    }

    async fillDescription(value: string): Promise<void> {
        await this.descriptionInput.fill(value);
    }

    async fillFullDescription(value: string): Promise<void> {
        await this.fullDescriptionEditor.fill(value);
    }

    async addKeyword(keyword: string): Promise<void> {
        await this.keywordsInput.fill(keyword);
        await this.keywordsInput.press('Enter');
    }

    async addKeywords(keywords: string[]): Promise<void> {
        for (const keyword of keywords) {
            await this.addKeyword(keyword);
        }
    }

    async toggleAllBranches(): Promise<void> {
        await this.allBranchesCheckbox.click();
    }

    async toggleNoExpiry(): Promise<void> {
        await this.noExpiryToggle.click();
    }

    async fillStartDate(value: string): Promise<void> {
        await this.startDateInput.fill(value);
    }

    async fillEndDate(value: string): Promise<void> {
        await this.endDateInput.fill(value);
    }

    async fillStartTime(hour: string, min: string): Promise<void> {
        await this.startTimeInput.fill(`${hour}:${min}`);
    }

    async fillEndTime(hour: string, min: string): Promise<void> {
        await this.endTimeInput.fill(`${hour}:${min}`);
    }

    /** Deal value type is a listbox-style control offering "%" or "Fixed". */
    async selectDealValueType(value: string): Promise<void> {
        await this.dealValueTypeSelect.click();
        await this.page.getByRole('option', { name: value, exact: true }).click();
    }

    async fillDealValue(value: string): Promise<void> {
        await this.dealValueInput.fill(value);
    }

    async selectCurrency(value: string): Promise<void> {
        await this.currencySelect.click();
        await this.page.getByRole('option', { name: value }).click();
    }

    async fillMinimumSpend(value: string): Promise<void> {
        await this.minimumSpendInput.fill(value);
    }

    async toggleUnlimitedQuantity(): Promise<void> {
        await this.unlimitedQuantityToggle.click();
        await expect(this.currentQuantityInput).toBeVisible();
    }

    async fillCurrentQuantity(value: string): Promise<void> {
        await this.currentQuantityInput.fill(value);
    }

    async clearTermsAndConditions(): Promise<void> {
        await this.termsEditor.click();
        await this.page.keyboard.press('ControlOrMeta+A');
        await this.page.keyboard.press('Backspace');
    }

    async resetTermsAndConditions(): Promise<void> {
        await this.resetTermsButton.click();
    }

    private async fillTermsAndConditions(value: string): Promise<void> {
        await this.termsEditor.fill(value);
    }
}
