import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';
import { ConfigBasePage } from '@pages/configuration/ConfigBasePage';
import { DealDesignStep } from './DealDesignStep';

export type DealDetailsData = {
    title: string;
    desc: string;
    fullDesc: string;
    keywords: string[];
    startDate: string;
    endDate: string;
    startHour: string;
    startMin: string;
    endHour: string;
    endMin: string;
    dealValue: string;
    minimumSpend: string;
    currentQuantity?: string;
    unlimitedQuantity?: boolean;
    terms?: string;
    resetToAutoGenerated?: boolean;
};

export class DealDetailsStep extends ConfigBasePage {
    private readonly pageTitle: Locator;

    private readonly inputDealTitle: Locator;
    private readonly inputDesc: Locator;
    private readonly inputFullDesc: Locator;
    private readonly inputKeywords: Locator;
    private readonly keywordLimitMessage: Locator;

    private readonly noExpiryToggle: Locator;
    private readonly startDateInput: Locator;
    private readonly endDateInput: Locator;
    private readonly startTimeInput: Locator;
    private readonly endTimeInput: Locator;
    private readonly dateTimeRangeError: Locator;

    private readonly dealValueTypeToggle: Locator;
    private readonly dealValueInput: Locator;
    private readonly currencySelect: Locator;
    private readonly minimumSpendInput: Locator;
    private readonly unlimitedQuantityToggle: Locator;
    private readonly currentQuantityInput: Locator;
    private readonly dealValueError: Locator;
    private readonly percentageDealValueError: Locator;
    private readonly quantityError: Locator;

    private readonly termsEditor: Locator;
    private readonly resetButton: Locator;
    private readonly termsRequiredError: Locator;

    private readonly validationError: Locator;
    private readonly nextButton: Locator;

    constructor(page: Page) {
        super(page);
        this.pageTitle = this.page.locator('form').getByText('General Details');

        // Deal Details is now a single page (General Details, Date & Time, Amount & Currency,
        // Terms & Conditions all rendered in this fixed vertical order), so unnamed/positional
        // locators below rely on that section order rather than per-step page isolation.
        this.inputDealTitle = this.page.getByRole('textbox').first();
        this.inputDesc = this.page.locator('textarea');
        this.inputFullDesc = this.page.locator('.tiptap').first();
        this.inputKeywords = this.page.getByRole('textbox', { name: 'Type keywords and press Enter' });
        this.keywordLimitMessage = this.page.getByText('Maximum 7 keywords allowed');

        this.noExpiryToggle = this.page.getByRole('switch', { name: 'Make deal indefinite' });
        this.startDateInput = this.page.getByRole('textbox', { name: 'YYYY-MM-DD' }).first();
        this.endDateInput = this.page.getByRole('textbox', { name: 'YYYY-MM-DD' }).nth(1);
        this.startTimeInput = this.page.getByRole('textbox', { name: 'Select time' }).first();
        this.endTimeInput = this.page.getByRole('textbox', { name: 'Select time' }).nth(1);
        this.dateTimeRangeError = this.page.getByText(/End (date|time) must be after start/i);

        this.dealValueTypeToggle = this.page.getByRole('combobox').filter({ hasText: '%' });
        this.dealValueInput = this.page.getByRole('spinbutton').first();
        this.currencySelect = this.page.getByRole('combobox').filter({ hasText: 'Singapore Dollar' });
        this.minimumSpendInput = this.page.getByText('Minimum Spend Minimum amount').getByRole('spinbutton');
        this.unlimitedQuantityToggle = this.page.getByRole('switch').last();
        this.currentQuantityInput = this.page.getByRole('spinbutton').nth(2);
        this.dealValueError = this.page.getByText('Deal value must be greater');
        this.percentageDealValueError = this.page.getByText('Percentage deal value must be between 0 and 100', { exact: true });
        this.quantityError = this.page.getByText('Quantity must be greater than');

        this.termsEditor = this.page.locator('.tiptap').last();
        this.resetButton = this.page.getByRole('button', { name: 'Reset to Auto-generated' });
        this.termsRequiredError = this.page.getByText('Terms & Conditions are required', { exact: true });

        this.validationError = this.page.getByRole('alert', { name: 'Please fix the following' });
        this.nextButton = this.page.getByRole('button', { name: 'Next', exact: true });
    }

    override async waitForReady(): Promise<void> {
        await super.waitForReady();
        await expect(this.pageTitle).toBeVisible();
    }

    async fill(data: DealDetailsData): Promise<void> {
        await this.fillDealTitle(data.title);
        await this.fillDescription(data.desc);
        await this.fillFullDescription(data.fullDesc);
        await this.addKeywords(data.keywords);

        await this.fillStartDate(data.startDate);
        await this.fillEndDate(data.endDate);
        await this.fillStartTime(data.startHour, data.startMin);
        await this.fillEndTime(data.endHour, data.endMin);

        await this.fillDealValue(data.dealValue);
        await this.fillMinimumSpend(data.minimumSpend);
        if (!data.unlimitedQuantity && data.currentQuantity) {
            await this.toggleUnlimitedQuantity();
            await this.fillCurrentQuantity(data.currentQuantity);
        }

        if (data.resetToAutoGenerated) {
            await this.resetTermsAndConditions();
        }
        if (data.terms !== undefined) {
            await this.fillTermsAndConditions(data.terms);
        }
    }

    async next(): Promise<DealDesignStep> {
        await this.nextButton.click();
        const designStep = new DealDesignStep(this.page);
        await designStep.waitForReady();
        return designStep;
    }

    async nextExpectingValidationError(): Promise<void> {
        await this.nextButton.click();
        await this.expectValidationError();
    }

    async expectTitleValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectDescriptionValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectStartDateValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectEndDateValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectEndDateBeforeStartError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.dateTimeRangeError).toBeVisible();
    }

    async expectEndTimeBeforeStartError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.dateTimeRangeError).toBeVisible();
    }

    async expectDealValueValidationError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.dealValueError).toBeVisible();
    }

    async expectPercentageDealValueValidationError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.percentageDealValueError).toBeVisible();
    }

    async expectQuantityValidationError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.quantityError).toBeVisible();
    }

    async expectTermsRequiredError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.termsRequiredError).toBeVisible();
    }

    async expectValidationError(): Promise<void> {
        await expect(this.validationError).toBeVisible();
    }

    async verifyKeywordLimit(): Promise<void> {
        await expect(this.keywordLimitMessage).toBeVisible();
    }

    async fillDealTitle(value: string): Promise<void> {
        await this.inputDealTitle.click();
        await this.inputDealTitle.fill(value);
    }

    async fillDescription(value: string): Promise<void> {
        await this.inputDesc.click();
        await this.inputDesc.fill(value);
    }

    async fillFullDescription(value: string): Promise<void> {
        await this.inputFullDesc.click();
        await this.inputFullDesc.fill(value);
    }

    async addKeyword(keyword: string): Promise<void> {
        await this.inputKeywords.click();
        await this.inputKeywords.fill(keyword);
        await this.inputKeywords.press('Enter');
    }

    async addKeywords(keywords: string[]): Promise<void> {
        for (const keyword of keywords) {
            await this.addKeyword(keyword);
        }
    }

    async toggleNoExpiry(): Promise<void> {
        await this.noExpiryToggle.click();
    }

    async fillStartDate(value: string): Promise<void> {
        await this.startDateInput.click();
        await this.startDateInput.fill(value);
    }

    async fillEndDate(value: string): Promise<void> {
        await this.endDateInput.click();
        await this.endDateInput.fill(value);
    }

    async fillStartTime(hour: string, min: string): Promise<void> {
        await this.startTimeInput.click();
        await this.startTimeInput.fill(`${hour}:${min}`);
    }

    async fillEndTime(hour: string, min: string): Promise<void> {
        await this.endTimeInput.click();
        await this.endTimeInput.fill(`${hour}:${min}`);
    }

    async selectDealValueType(value: string): Promise<void> {
        await this.dealValueTypeToggle.selectOption(value);
    }

    async fillDealValue(value: string): Promise<void> {
        await this.dealValueInput.click();
        await this.dealValueInput.fill(value);
    }

    async selectCurrency(value: string): Promise<void> {
        await this.currencySelect.selectOption(value);
    }

    async fillMinimumSpend(value: string): Promise<void> {
        await this.minimumSpendInput.click();
        await this.minimumSpendInput.fill(value);
    }

    async toggleUnlimitedQuantity(): Promise<void> {
        await this.unlimitedQuantityToggle.click();
    }

    async fillCurrentQuantity(value: string): Promise<void> {
        await this.currentQuantityInput.click();
        await this.currentQuantityInput.fill(value);
    }

    async clearTermsAndConditions(): Promise<void> {
        await this.termsEditor.click();
        await this.page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A');
        await this.page.keyboard.press('Backspace');
    }

    async resetTermsAndConditions(): Promise<void> {
        await this.resetButton.click();
    }

    private async fillTermsAndConditions(value: string): Promise<void> {
        await this.termsEditor.click();
        await this.termsEditor.fill(value);
    }
}
