import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';
import { ConfigBasePage } from '@pages/configuration/ConfigBasePage';
import { PreviewStep } from './PreviewStep';

type TermsData = {
    terms?: string;
    resetToAutoGenerated?: boolean;
};

export class TncStep extends ConfigBasePage {
    private readonly pageTitle: Locator;
    private readonly termsEditor: Locator;
    private readonly resetButton: Locator;
    private readonly validationError: Locator;
    private readonly termsRequiredError: Locator;
    private readonly nextButton: Locator;

    constructor(page: Page) {
        super(page);
        this.pageTitle = this.page.locator('form').getByText('Terms & Conditions');
        this.termsEditor = this.page.locator('.tiptap');
        this.resetButton = this.page.getByRole('button', { name: 'Reset to Auto-generated' });
        this.validationError = this.page.getByRole('alert', { name: 'Please fix the following' });
        this.termsRequiredError = this.page.getByText('Terms & Conditions are required', { exact: true });
        this.nextButton = this.page.getByRole('button', { name: 'Next', exact: true });
    }

    override async waitForReady(): Promise<void> {
        await super.waitForReady();
        await expect(this.pageTitle).toBeVisible();
    }

    async fill(data: TermsData): Promise<void> {
        if (data.resetToAutoGenerated) {
            await this.resetTermsAndConditions();
        }

        if (data.terms !== undefined) {
            await this.fillTermsAndConditions(data.terms);
        }
    }

    async next(): Promise<PreviewStep> {
        await this.nextButton.click();
        const previewStep = new PreviewStep(this.page);
        await previewStep.waitForReady();
        return previewStep;
    }

    async nextExpectingValidationError(): Promise<void> {
        await this.nextButton.click();
        await this.expectValidationError();
    }

    async expectTermsRequiredError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.termsRequiredError).toBeVisible();
    }

    async expectValidationError(): Promise<void> {
        await expect(this.validationError).toBeVisible();
    }

    async clearTermsAndConditions(): Promise<void> {
        await this.termsEditor.click();
        await this.page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A');
        await this.page.keyboard.press('Backspace');
    }

    async resetTermsAndConditions(): Promise<void> {
        await this.resetButton.click();
    }

    private async fillTermsAndConditions(value: string): Promise<void> {
        await this.termsEditor.click();
        await this.termsEditor.fill(value);
    }
}
