import type { Page, Locator } from '@playwright/test';
import { expect } from '@playwright/test';
import { ConfigBasePage } from '@pages/configuration/ConfigBasePage';
import { generateLoyaltyProgramTitle } from '../../../../../testDataGenerators';
import { LoyaltyDesignStep } from './LoyaltyDesignStep';

export type ProgramConfigurationData = {
    programType: string;
    visitsPerStamp: string;
    completionThreshold?: string;
};

export const DEFAULT_PROGRAM_CONFIGURATION: ProgramConfigurationData = {
    programType: 'Visit-Based (Count Visits)',
    visitsPerStamp: '1',
};

export type LoyaltyGeneralDetailsData = {
    title: string;
    description: string;
    fullDescription: string;
    keywords: string[];
    startDate: string;
    endDate: string;
};

export type RewardData = {
    milestone: string;
    name: string;
    description: string;
    validUntil: string;
    quantity: string;
};

export type LoyaltyDetailsData = ProgramConfigurationData & LoyaltyGeneralDetailsData & {
    terms?: string;
    resetToAutoGenerated?: boolean;
};

export class LoyaltyDetailsStep extends ConfigBasePage {
    private readonly pageTitle: Locator;

    // Program Configuration
    private readonly programTypeDropdown: Locator;
    private readonly visitsPerStampInput: Locator;
    private readonly completionThresholdInput: Locator;
    private readonly autoRenewToggle: Locator;
    private readonly visitsPerStampError: Locator;
    private readonly amountPerStampError: Locator;

    // General Details
    private readonly programTitleInput: Locator;
    private readonly descriptionInput: Locator;
    private readonly fullDescriptionEditor: Locator;
    private readonly keywordsInput: Locator;
    private readonly noExpiryToggle: Locator;
    private readonly startDateInput: Locator;
    private readonly endDateInput: Locator;

    // Rewards Configuration
    private readonly addRewardButton: Locator;
    private readonly rewardMilestoneInput: Locator;
    private readonly rewardNameInput: Locator;
    private readonly rewardDescriptionEditor: Locator;
    private readonly rewardValidUntilInput: Locator;
    private readonly rewardQuantityInput: Locator;
    private readonly nextRewardButton: Locator;
    private readonly previousRewardButton: Locator;

    // Terms & Conditions
    private readonly termsEditor: Locator;
    private readonly resetButton: Locator;
    private readonly termsRequiredError: Locator;

    private readonly validationError: Locator;
    private readonly nextButton: Locator;

    constructor(page: Page) {
        super(page);
        this.pageTitle = this.page.locator('form').getByText('Program Configuration');

        this.programTypeDropdown = this.page.getByRole('combobox').filter({ hasText: /Visit-Based|Transaction-Based/ });
        // Loyalty Program Details is now a single page (Program Configuration, General Details,
        // Rewards Configuration, Terms & Conditions all rendered in this fixed vertical order), so
        // unnamed/positional locators below rely on that section order.
        this.visitsPerStampInput = this.page.getByRole('spinbutton').nth(0);
        this.completionThresholdInput = this.page.getByRole('spinbutton').nth(1);
        this.autoRenewToggle = this.page.getByRole('switch', { name: 'Auto-renew loyalty card on completion' });
        this.visitsPerStampError = this.page.getByText('Visits per stamp must be at least');
        this.amountPerStampError = this.page.getByText('Amount per stamp must be at least');

        this.programTitleInput = this.page.getByRole('textbox').nth(0);
        this.descriptionInput = this.page.locator('textarea').first();
        this.fullDescriptionEditor = this.page.locator('.tiptap').nth(0);
        this.keywordsInput = this.page.getByRole('textbox', { name: 'Type keywords and press Enter' });
        this.noExpiryToggle = this.page.getByRole('switch', { name: 'Make loyalty program indefinite' });
        this.startDateInput = this.page.getByRole('textbox', { name: 'YYYY-MM-DD' }).nth(0);
        this.endDateInput = this.page.getByRole('textbox', { name: 'YYYY-MM-DD' }).nth(1);

        this.addRewardButton = this.page.getByRole('button', { name: 'Add Reward', exact: true });
        this.rewardMilestoneInput = this.page.getByRole('spinbutton').nth(2);
        // getByRole('textbox') matches every textbox on the page regardless of accessible name,
        // so this index counts through Program Title(0), Description(1), Keywords(2),
        // Start Date(3), End Date(4) before reaching the unnamed Reward Name input at index 5.
        this.rewardNameInput = this.page.getByRole('textbox').nth(5);
        this.rewardDescriptionEditor = this.page.locator('.tiptap').nth(1);
        this.rewardValidUntilInput = this.page.getByRole('textbox', { name: 'YYYY-MM-DD' }).nth(2);
        this.rewardQuantityInput = this.page.getByRole('spinbutton').nth(3);
        this.nextRewardButton = this.page.getByRole('button', { name: 'Next' }).first();
        this.previousRewardButton = this.page.getByRole('button', { name: 'Prev' }).first();

        this.termsEditor = this.page.locator('.tiptap').nth(2);
        this.resetButton = this.page.getByRole('button', { name: 'Reset to Auto-generated' });
        this.termsRequiredError = this.page.getByText('Terms & Conditions are required', { exact: true });

        this.validationError = this.page.getByRole('alert', { name: 'Please fix the following' });
        this.nextButton = this.page.getByRole('button', { name: 'Next', exact: true }).nth(1);
    }

    static validGeneralDetails(overrides: Partial<LoyaltyGeneralDetailsData> = {}): LoyaltyGeneralDetailsData {
        return {
            title: generateLoyaltyProgramTitle(),
            description: 'Test loyalty program description',
            fullDescription: 'Full description for an automated loyalty program.',
            keywords: ['loyalty', 'uat', 'test'],
            startDate: LoyaltyDetailsStep.futureDate(7),
            endDate: LoyaltyDetailsStep.futureDate(60),
            ...overrides,
        };
    }

    static validReward(overrides: Partial<RewardData> = {}): RewardData {
        return {
            milestone: '10',
            name: 'Test Reward',
            description: 'Test reward description',
            validUntil: LoyaltyDetailsStep.futureDate(90),
            quantity: '1000',
            ...overrides,
        };
    }

    private static futureDate(daysFromNow: number): string {
        const date = new Date(Date.now() + daysFromNow * 24 * 60 * 60 * 1000);
        return date.toISOString().slice(0, 10);
    }

    override async waitForReady(): Promise<void> {
        await super.waitForReady();
        await expect(this.pageTitle).toBeVisible();
    }

    async fillProgramConfiguration(data: ProgramConfigurationData): Promise<void> {
        await this.selectProgramType(data.programType);
        await this.fillVisitsPerStamp(data.visitsPerStamp);
        if (data.completionThreshold) {
            await this.fillCompletionThreshold(data.completionThreshold);
        }
    }

    async fillGeneralDetails(data: LoyaltyGeneralDetailsData): Promise<void> {
        await this.fillProgramTitle(data.title);
        await this.fillDescription(data.description);
        await this.fillFullDescription(data.fullDescription);
        await this.addKeywords(data.keywords);
        await this.fillStartDate(data.startDate);
        await this.fillEndDate(data.endDate);
    }

    async fillCurrentReward(data: RewardData): Promise<void> {
        await this.fillRewardMilestone(data.milestone);
        await this.fillRewardName(data.name);
        await this.fillRewardDescription(data.description);
        await this.fillRewardValidUntil(data.validUntil);
        await this.fillRewardQuantity(data.quantity);
    }

    async fillCurrentRewardExcept(data: RewardData, omittedField: keyof RewardData): Promise<void> {
        if (omittedField !== 'milestone') {
            await this.fillRewardMilestone(data.milestone);
        } else { await this.clearRewardMilestone(); }

        if (omittedField !== 'name') {
            await this.fillRewardName(data.name);
        } else {
            await this.clearRewardName();
        }
        if (omittedField !== 'description') {
            await this.fillRewardDescription(data.description);
        }
        if (omittedField !== 'validUntil') {
            await this.fillRewardValidUntil(data.validUntil);
        } else {
            await this.clearRewardValidUntil();
        }
        if (omittedField !== 'quantity') {
            await this.fillRewardQuantity(data.quantity);
        } else {
            await this.clearRewardQuantity();
        }
    }

    async fillRewards(data: RewardData, count: number): Promise<void> {
        for (let rewardIndex = 2; rewardIndex <= count; rewardIndex++) {
            await this.addReward();
        }

        for (let rewardIndex = 2; rewardIndex <= count; rewardIndex++) {
            await this.previousReward();
        }

        for (let rewardIndex = 1; rewardIndex <= count; rewardIndex++) {
            await this.fillCurrentReward({
                ...data,
                name: `${data.name} ${rewardIndex}`,
            });

            if (rewardIndex < count) {
                await this.nextReward();
            }
        }
    }

    async fillTerms(data: { terms?: string; resetToAutoGenerated?: boolean }): Promise<void> {
        if (data.resetToAutoGenerated) {
            await this.resetTermsAndConditions();
        }
        if (data.terms !== undefined) {
            await this.fillTermsAndConditions(data.terms);
        }
    }

    async addRewardsUntilMaximum(): Promise<void> {
        for (let rewardCount = 2; rewardCount <= 5; rewardCount++) {
            await this.addReward();
        }
    }

    async addReward(): Promise<void> {
        await expect(this.addRewardButton).toBeEnabled();
        await this.addRewardButton.click();
    }

    async nextReward(): Promise<void> {
        await expect(this.nextRewardButton).toBeEnabled();
        await this.nextRewardButton.click();
    }

    async previousReward(): Promise<void> {
        await expect(this.previousRewardButton).toBeEnabled();
        await this.previousRewardButton.click();
    }

    async next(): Promise<LoyaltyDesignStep> {
        await this.nextButton.click();
        const designStep = new LoyaltyDesignStep(this.page);
        await designStep.waitForReady();
        return designStep;
    }

    async nextExpectingValidationError(): Promise<void> {
        await this.nextButton.click();
        await this.expectValidationError();
    }

    async selectProgramType(value: string): Promise<void> {
        await this.programTypeDropdown.click();
        await this.page.getByRole('option', { name: value }).click();
    }

    async fillVisitsPerStamp(value: string): Promise<void> {
        await this.visitsPerStampInput.click();
        await this.visitsPerStampInput.fill(value);
    }

    async fillAmountPerStamp(value: string): Promise<void> {
        await this.fillVisitsPerStamp(value);
    }

    async fillCompletionThreshold(value: string): Promise<void> {
        await this.completionThresholdInput.click();
        await this.completionThresholdInput.fill(value);
    }

    async toggleAutoRenew(): Promise<void> {
        await this.autoRenewToggle.click();
    }

    async fillProgramTitle(value: string): Promise<void> {
        await this.programTitleInput.click();
        await this.programTitleInput.fill(value);
    }

    async fillDescription(value: string): Promise<void> {
        await this.descriptionInput.click();
        await this.descriptionInput.fill(value);
    }

    async fillFullDescription(value: string): Promise<void> {
        await this.fullDescriptionEditor.click();
        await this.fullDescriptionEditor.fill(value);
    }

    async addKeyword(keyword: string): Promise<void> {
        await this.keywordsInput.click();
        await this.keywordsInput.fill(keyword);
        await this.keywordsInput.press('Enter');
    }

    async addKeywords(keywords: string[]): Promise<void> {
        for (const keyword of keywords) {
            await this.addKeyword(keyword);
        }
    }

    async toggleNoExpiry(): Promise<void> {
        await this.noExpiryToggle.click();
    }

    async fillStartDate(value: string): Promise<void> {
        await this.startDateInput.click();
        await this.startDateInput.fill(value);
    }

    async fillEndDate(value: string): Promise<void> {
        await this.endDateInput.click();
        await this.endDateInput.fill(value);
    }

    async fillRewardMilestone(value: string): Promise<void> {
        await this.rewardMilestoneInput.click();
        await this.rewardMilestoneInput.fill(value);
    }

    async clearRewardMilestone(): Promise<void> {
        await this.rewardMilestoneInput.click();
        await this.rewardMilestoneInput.fill('');
    }

    async fillRewardName(value: string): Promise<void> {
        await this.rewardNameInput.click();
        await this.rewardNameInput.fill(value);
    }

    async clearRewardName(): Promise<void> {
        await this.rewardNameInput.click();
        await this.rewardNameInput.fill('');
    }

    async fillRewardDescription(value: string): Promise<void> {
        await this.rewardDescriptionEditor.click();
        await this.rewardDescriptionEditor.fill(value);
    }

    async fillRewardValidUntil(value: string): Promise<void> {
        await this.rewardValidUntilInput.click();
        await this.rewardValidUntilInput.fill(value);
    }

    async clearRewardValidUntil(): Promise<void> {
        await this.rewardValidUntilInput.click();
        await this.rewardValidUntilInput.fill('');
    }

    async fillRewardQuantity(value: string): Promise<void> {
        await this.rewardQuantityInput.click();
        await this.rewardQuantityInput.fill(value);
    }

    async clearRewardQuantity(): Promise<void> {
        await this.rewardQuantityInput.click();
        await this.rewardQuantityInput.fill('');
    }

    async resetTermsAndConditions(): Promise<void> {
        await this.resetButton.click();
    }

    private async fillTermsAndConditions(value: string): Promise<void> {
        await this.termsEditor.click();
        await this.termsEditor.fill(value);
    }

    async expectAddRewardDisabled(): Promise<void> {
        await expect(this.addRewardButton).toBeDisabled();
    }

    async expectVisitsPerStampValidationError(): Promise<void> {
        await expect(this.visitsPerStampError).toBeVisible();
    }

    async expectAmountPerStampValidationError(): Promise<void> {
        await expect(this.amountPerStampError).toBeVisible();
    }

    async expectTitleValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectDescriptionValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectDateValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectRewardMilestoneValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectRewardNameValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectRewardValidUntilValidationError(): Promise<void> {
        await this.expectValidationError();
    }

    async expectTermsRequiredError(): Promise<void> {
        await this.expectValidationError();
        await expect(this.termsRequiredError).toBeVisible();
    }

    async expectValidationError(): Promise<void> {
        await expect(this.validationError).toBeVisible();
    }
}
